Fix status checking for non-running cases.

diff --git a/resources/hrmd_lsb-init b/resources/hrmd_lsb-init
--- a/resources/hrmd_lsb-init
+++ b/resources/hrmd_lsb-init
@@ -54,8 +54,12 @@ force_reload() {
 
 status() {
     daemon_wrapper="${HRM_HOME}/bin/hrm_queuemanager"
+    # temporarily disable exit-on-error, as we are evaluating the exit status
+    # anyway below and want to show reasonable messages:
+    set +e
     HRMD_PID=$(pidofproc -p $PID_FILE "$daemon_wrapper")
     status=$?
+    set -e
     # print the current status of the service
     if [ "$status" = 0 ]; then
         log_success_msg "HRM is running ($daemon_wrapper), PID: $HRMD_PID"
